<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="FB_OPCUA_GetRecipe" Id="{b1ef5857-878b-4c27-b000-1c88dc25d3c5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_OPCUA_GetRecipe
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_OPCUA_GetRecipe">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>